# file ini merupakan orkestrasi untuk menjalankan server surreal
version: '3'

services:

  # DATABASE
  db:
    image: postgres:alpine
    container_name: db
    # nilai env (pada file .env di server)
    # setidaknya membutuhkan dua nilai, POSTGRES_USER dan POSTGRESS_PASSWORD
    env_file:
      - .env
    restart: unless-stopped
    # set shared memory limit
    shm_size: 128mb
    # port
    port: '5432:5432'
    # mount volume db dengan direktori db pada host
    # memerlukan running image postgres dan setup
    # direktori ./db pertama kali
    volumes:
      - ./db:/var/lib/postgresql/data

  # CACHE
  cache:
    # pull image redis
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    # port
    port: '6379:6379'
    # run
    command: redis-server /usr/local/etc/redis/redis.conf
    # redis.conf terletak pada folder ./cache di host
    volumes:
      - ./cache:/usr/local/etc/redis
    
  # WEB SERVER
  surreal:
    image: j0hanespao/surreal:latest
    container_name: surreal
    restart: unless-stopped
    port: '3000:3000'
    depends_on:
      - db
      - cache

  # PROXY SERVER
  proxy:
    image: nginx:alpine-slim
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem
